/** originally generated by csmith 2.0.0 with seed 2063678216 */

int *g_46 = 0;
int *g_63 = 0;

void func_17(int p_21)
{
	for (;;) {
		(*g_46) += 0;
		if (p_21)
		{
			(*g_63) = 0;
		}
		(*g_63) = 0;
	}
}

int main (int argc, char* argv[])
{
    return 0;
}
