/** originally generated by csmith 2.0.0 with seed 1870488464 */

struct S0 {
   int f0;
};

int g_3 = 8L;
struct S0 g_325 = {};
struct S0 g_376 = {};

int func_10()
{
	int i, j, k;
	for (i = 0; i < 10; i++) { }
	for (i = 0; i < 10; i++)
	{
lbl_583:
		;
	}
	for (g_3 = 16; (g_3 <= 13); g_3 = (1))
	{
		if (g_376.f0 && g_325.f0)
				goto lbl_583;
	}
	return 0;
}

int main (int argc, char* argv[])
{
    return 0;
}
